# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u9879\u76eeid')),
                ('project_name', models.CharField(max_length=60, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('git_ssh_address', models.CharField(max_length=255, verbose_name='git ssh\u5730\u5740')),
                ('dir_address', models.CharField(max_length=160, verbose_name='\u9879\u76ee\u8def\u5f84\u5730\u5740')),
                ('is_cluster', models.SmallIntegerField(default=0, verbose_name='\u662f\u5426\u96c6\u7fa4\u6a21\u5f0f')),
                ('describe', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
