# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('release_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u4e0a\u7ebf\u5de5\u5355id')),
                ('project_id', models.IntegerField(default=0, verbose_name='\u9879\u76eeid')),
                ('title', models.CharField(max_length=60, verbose_name='\u6807\u9898')),
                ('branch', models.CharField(max_length=160, verbose_name='\u5206\u652f')),
                ('version', models.CharField(max_length=80, verbose_name='\u7248\u672c')),
                ('backup_name', models.CharField(max_length=255, verbose_name='\u5907\u4efd\u5206\u652f\u540d\u79f0(\u4ee5backup_\u5f00\u5934)')),
                ('status', models.SmallIntegerField(default=0, verbose_name='\u72b6\u6001[ 0\u672a\u53d1\u5e03, 1\u5df2\u53d1\u5e03, 2\u5df2\u56de\u6eda ]')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
